<?php

/**
 * PluginToodledoAccount
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginToodledoAccount extends BaseToodledoAccount
{
  /**
   * Gets an instance of shesek's Toodledo class 
   * @param string $appid
   * @return Toodledo
   */
  public function connect($appid = null)
  {
    return new Toodledo($this->getUserid(), $this->getPassword(), $appid);
  }
}